### ISSUE TITLE
CocoaPods could not find compatible versions for pod "vital-core-react-native"

### ISSUE THREAD

**Issue by itsramiel** [tryVital/vital-react-native#19]
Hello there 👋

I am trying out vital, so I created a new react native project and added the dependencies as mentioned by the docs:
```
yarn add @tryvital/vital-core-react-native
yarn add @tryvital/vital-health-react-native
yarn add @tryvital/vital-devices-react-native

yarn install
```

However while linking the dependencies in the next step using:
```
cd ios
pod install
```

I get the following error message:

```
[!] CocoaPods could not find compatible versions for pod "vital-core-react-native":
  In Podfile:
    vital-core-react-native (from `../node_modules/@tryvital/vital-core-react-native`)

Specs satisfying the `vital-core-react-native (from `../node_modules/@tryvital/vital-core-react-native`)` dependency were found, but they required a higher minimum deployment target.
```

The minimum deployment target is 12.4 as is in the example app. I tried bumping it up to 13 or higher, but did not work.

Let me know if you need any more info

**Comment by andersio** [comment]
Hi @itsramiel,

I assumed you have created the project through the React Native CLI. If so, you will need to update the minimum deployment target specified in your Podfile as well.

```diff
-platform :ios, min_ios_version_supported
+platform :ios, '14.0'
```

**Comment by itsramiel** [comment]
I thought min_ios_version_supported is read from the value in xcode. Thank you

**Comment by itsramiel** [comment]
Would be worth mentioning it in the docs 👍
