### ISSUE TITLE
setUserId crashes the iOS app when the bundle is reloaded/in release build

### ISSUE THREAD

**Issue by kubik369** [tryVital/vital-react-native#29]
Hi,

we are working on integrating your SDK and I have encountered some problems on the iOS side. At the start, it was randomly crashing. I have kind of ignored it, since I couldn't replicate it, but our release build crashes because of it right when we open it, so here I am 😅

After an investigation, in our app, I was able to replicate the issue by simply reloading the bundle (`r` in metro or shake screen and select `Reload JS bundle`). It seems to be crashing in the VitalCore/VitalClient.swift file on line 304, which is the `_setUserId` function. This is basically all the relevant code on our side (I have checked the parameters, they seem to be fine):
```
useEffect(() => {
  const loadVitalHealthSDK = async () => {
    if (!config) {
      return
    }

    const {apiKey, environment, region, userId} = config

    try {
      await VitalHealth.configureClient(apiKey, environment, region, true)
      await VitalHealth.configure(new HealthConfig())
      await VitalHealth.setUserId(userId)
      setIsVitalHealthAvailable(true)
    } catch (error) {
      ...
    }
  }

  loadVitalHealthSDK()

  return () => {
    VitalHealth.cleanUp()
  }
}, [config, t])
```

I tested locally with the following:
Apple Mac Pro 14 M1 Pro
Xcode 14.2/14.3
iOS 16.2/16.4
React Native 0.70.7
React 18.2.0

I went ahead and tried to replicate this issue in your example app. I didn't get to the same spot, but your example app also crashes when I reload the bundle. I have simply built the app, ran it and reloaded the bundle.

Android side does not seem to have these issues, but I will have to confirm with my colleague after holidays :)

**Comment by andersio** [comment]
Hi, which version of the packages are being used?

**Comment by kubik369** [comment]
Sorry, completely forgot about that! Should be the newest ones.

In our app, we have these in our package.json:
```
@tryvital/vital-core-react-native@1.4.1
@tryvital/vital-health-react-native@1.4.1
```
In Podfile.lock, I found these, just for the sake of completion:
```
- vital-core-react-native (1.4.1):
    - React-Core
    - VitalCore (~> 0.9.3)
  - vital-health-react-native (1.4.1):
    - React-Core
    - VitalHealthKit (~> 0.9.3)
  - VitalCore (0.9.3)
  - VitalHealthKit (0.9.3):
    - VitalCore (~> 0.9.3)
```
The same versions have been installed when I tried the example app :)

**Comment by d-vincent** [comment]
I am also experiencing this issue.

**Comment by d-vincent** [comment]
@andersio I am having issues installing the new version `1.5.0` on iOS. 

Steps: 
`yarn add @tryvital/vital-core-react-native`
`yarn add @tryvital/vital-health-react-native`
`cd ios`
`pod install`

Output: 
[!] CocoaPods could not find compatible versions for pod "VitalHealthKit":
  In Podfile:
    vital-health-react-native (from `../node_modules/@tryvital/vital-health-react-native`) was resolved to 1.5.0, which depends on
      VitalHealthKit (~> 0.9.4)

None of your spec sources contain a spec satisfying the dependency: `VitalHealthKit (~> 0.9.4)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by andersio** [comment]
@d-vincent  Run `pod repo update`.

**Comment by kubik369** [comment]
Hi @andersio! I have updated the package to the newer version and moved the clean up function, as per your suggestion. Everything seems to be working fine now! Thanks for the help :)
