### ISSUE TITLE
Support for Expo?

### ISSUE THREAD

**Issue by anthomaxcool** [tryVital/vital-react-native#38]
Hi, I'm not sure if this is the right place..

I'm using react-native with Expo. I wish to handle the api_key server side only and I'm using expo client side. From what I understand reading the code, it cannot work if using Expo.

I'm wondering if there's some way to make this work using Expo, or if I need to handle the wearables some other way ? (maybe by having a web page and render this page instead, since I can generate the token server side if I'm using the react libraries client side)

Or are there other options I should consider?

**Comment by maitham** [comment]
Sorry for the late reply, currently Expo isn't supported by this library. You can however call our API's directly from Expo, or call Vital's APIs directly from your server.
