### ISSUE TITLE
Module was compiled with an incompatible version of Kotlin

### ISSUE THREAD

**Issue by dipak-agile** [tryVital/vital-react-native#48]
**Hello There,**

**While build for the release apk, getting the below error.** 

`/Users/dipakagile/.gradle/caches/transforms-3/01fdb81295289246b6fbe3c8aa224020/transformed/jetified-VitalClient-1.0.0-beta.16-api.jar!/META-INF/VitalClient_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.`

**I have tried changing the kotlin version in root build.gradle but still same issue.**

**Comment by maitham** [comment]
This should be fixed now.
